//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DesktopCleaner.Potatoes {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="n_distrep_wsSoap", Namespace="http://tempurl.org")]
    public partial class n_distrep_ws : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback log_errorOperationCompleted;
        
        private System.Threading.SendOrPostCallback run_distrepOperationCompleted;
        
        private System.Threading.SendOrPostCallback run_distrep_extOperationCompleted;
        
        private System.Threading.SendOrPostCallback run_distrep_with_envOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public n_distrep_ws() {
            this.Url = global::DesktopCleaner.Properties.Settings.Default.DesktopCleaner_Potatoes_n_distrep_ws;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event log_errorCompletedEventHandler log_errorCompleted;
        
        /// <remarks/>
        public event run_distrepCompletedEventHandler run_distrepCompleted;
        
        /// <remarks/>
        public event run_distrep_extCompletedEventHandler run_distrep_extCompleted;
        
        /// <remarks/>
        public event run_distrep_with_envCompletedEventHandler run_distrep_with_envCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempurl.org/log_error", RequestNamespace="http://tempurl.org", ResponseNamespace="http://tempurl.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public s_rep_return log_error(string as_message) {
            object[] results = this.Invoke("log_error", new object[] {
                        as_message});
            return ((s_rep_return)(results[0]));
        }
        
        /// <remarks/>
        public void log_errorAsync(string as_message) {
            this.log_errorAsync(as_message, null);
        }
        
        /// <remarks/>
        public void log_errorAsync(string as_message, object userState) {
            if ((this.log_errorOperationCompleted == null)) {
                this.log_errorOperationCompleted = new System.Threading.SendOrPostCallback(this.Onlog_errorOperationCompleted);
            }
            this.InvokeAsync("log_error", new object[] {
                        as_message}, this.log_errorOperationCompleted, userState);
        }
        
        private void Onlog_errorOperationCompleted(object arg) {
            if ((this.log_errorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.log_errorCompleted(this, new log_errorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempurl.org/run_distrep", RequestNamespace="http://tempurl.org", ResponseNamespace="http://tempurl.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public s_rep_return run_distrep(int al_report_id, string as_format_extension, string[] as_args, string[] as_arg_types) {
            object[] results = this.Invoke("run_distrep", new object[] {
                        al_report_id,
                        as_format_extension,
                        as_args,
                        as_arg_types});
            return ((s_rep_return)(results[0]));
        }
        
        /// <remarks/>
        public void run_distrepAsync(int al_report_id, string as_format_extension, string[] as_args, string[] as_arg_types) {
            this.run_distrepAsync(al_report_id, as_format_extension, as_args, as_arg_types, null);
        }
        
        /// <remarks/>
        public void run_distrepAsync(int al_report_id, string as_format_extension, string[] as_args, string[] as_arg_types, object userState) {
            if ((this.run_distrepOperationCompleted == null)) {
                this.run_distrepOperationCompleted = new System.Threading.SendOrPostCallback(this.Onrun_distrepOperationCompleted);
            }
            this.InvokeAsync("run_distrep", new object[] {
                        al_report_id,
                        as_format_extension,
                        as_args,
                        as_arg_types}, this.run_distrepOperationCompleted, userState);
        }
        
        private void Onrun_distrepOperationCompleted(object arg) {
            if ((this.run_distrepCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.run_distrepCompleted(this, new run_distrepCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempurl.org/run_distrep_ext", RequestNamespace="http://tempurl.org", ResponseNamespace="http://tempurl.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public s_rep_return run_distrep_ext(int al_report_id, string as_output_extension, string[] as_args, string[] as_arg_types, bool ab_dev_mode) {
            object[] results = this.Invoke("run_distrep_ext", new object[] {
                        al_report_id,
                        as_output_extension,
                        as_args,
                        as_arg_types,
                        ab_dev_mode});
            return ((s_rep_return)(results[0]));
        }
        
        /// <remarks/>
        public void run_distrep_extAsync(int al_report_id, string as_output_extension, string[] as_args, string[] as_arg_types, bool ab_dev_mode) {
            this.run_distrep_extAsync(al_report_id, as_output_extension, as_args, as_arg_types, ab_dev_mode, null);
        }
        
        /// <remarks/>
        public void run_distrep_extAsync(int al_report_id, string as_output_extension, string[] as_args, string[] as_arg_types, bool ab_dev_mode, object userState) {
            if ((this.run_distrep_extOperationCompleted == null)) {
                this.run_distrep_extOperationCompleted = new System.Threading.SendOrPostCallback(this.Onrun_distrep_extOperationCompleted);
            }
            this.InvokeAsync("run_distrep_ext", new object[] {
                        al_report_id,
                        as_output_extension,
                        as_args,
                        as_arg_types,
                        ab_dev_mode}, this.run_distrep_extOperationCompleted, userState);
        }
        
        private void Onrun_distrep_extOperationCompleted(object arg) {
            if ((this.run_distrep_extCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.run_distrep_extCompleted(this, new run_distrep_extCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempurl.org/run_distrep_with_env", RequestNamespace="http://tempurl.org", ResponseNamespace="http://tempurl.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public s_rep_return run_distrep_with_env(int al_report_id, string as_output_extension, string[] as_args, string[] as_arg_types, string as_environment) {
            object[] results = this.Invoke("run_distrep_with_env", new object[] {
                        al_report_id,
                        as_output_extension,
                        as_args,
                        as_arg_types,
                        as_environment});
            return ((s_rep_return)(results[0]));
        }
        
        /// <remarks/>
        public void run_distrep_with_envAsync(int al_report_id, string as_output_extension, string[] as_args, string[] as_arg_types, string as_environment) {
            this.run_distrep_with_envAsync(al_report_id, as_output_extension, as_args, as_arg_types, as_environment, null);
        }
        
        /// <remarks/>
        public void run_distrep_with_envAsync(int al_report_id, string as_output_extension, string[] as_args, string[] as_arg_types, string as_environment, object userState) {
            if ((this.run_distrep_with_envOperationCompleted == null)) {
                this.run_distrep_with_envOperationCompleted = new System.Threading.SendOrPostCallback(this.Onrun_distrep_with_envOperationCompleted);
            }
            this.InvokeAsync("run_distrep_with_env", new object[] {
                        al_report_id,
                        as_output_extension,
                        as_args,
                        as_arg_types,
                        as_environment}, this.run_distrep_with_envOperationCompleted, userState);
        }
        
        private void Onrun_distrep_with_envOperationCompleted(object arg) {
            if ((this.run_distrep_with_envCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.run_distrep_with_envCompleted(this, new run_distrep_with_envCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempurl.org")]
    public partial class s_rep_return {
        
        private int return_codeField;
        
        private string return_messageField;
        
        private byte[] blob_dataField;
        
        /// <remarks/>
        public int return_code {
            get {
                return this.return_codeField;
            }
            set {
                this.return_codeField = value;
            }
        }
        
        /// <remarks/>
        public string return_message {
            get {
                return this.return_messageField;
            }
            set {
                this.return_messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] blob_data {
            get {
                return this.blob_dataField;
            }
            set {
                this.blob_dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void log_errorCompletedEventHandler(object sender, log_errorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class log_errorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal log_errorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public s_rep_return Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((s_rep_return)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void run_distrepCompletedEventHandler(object sender, run_distrepCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class run_distrepCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal run_distrepCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public s_rep_return Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((s_rep_return)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void run_distrep_extCompletedEventHandler(object sender, run_distrep_extCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class run_distrep_extCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal run_distrep_extCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public s_rep_return Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((s_rep_return)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void run_distrep_with_envCompletedEventHandler(object sender, run_distrep_with_envCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class run_distrep_with_envCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal run_distrep_with_envCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public s_rep_return Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((s_rep_return)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591